import type { NailSet } from '@/types';

export const nailSets: NailSet[] = [
  {
    id: 'blush-boba-french',
    code: 'BNB-001',
    name: 'Blush Boba French',
    category: 'French',
    length: 'Medium',
    shape: 'Almond',
    finish: 'Gloss',
    price: 899,
    color: 'Blush pink',
    tone: '#ffd5e3',
    accentTone: '#d7c5ff',
    description: 'A soft blush French set with a clean glossy finish and rounded almond silhouette.',
    story: 'Quietly cute, polished and easy to wear with almost everything.',
    productionTime: '4–6 working days',
    featured: true,
  },
  {
    id: 'lavender-milk-glaze',
    code: 'BNB-002',
    name: 'Lavender Milk Glaze',
    category: 'Minimal',
    length: 'Short',
    shape: 'Oval',
    finish: 'Pearl',
    price: 799,
    color: 'Lavender',
    tone: '#d9c7ff',
    accentTone: '#ffe0ef',
    description: 'A dreamy lavender milk set with a soft pearl glow and everyday-friendly length.',
    story: 'Made for clean outfits, soft studio light and low-effort polish.',
    productionTime: '3–5 working days',
    featured: true,
  },
  {
    id: 'cat-eye-mocha',
    code: 'BNB-003',
    name: 'Cat Eye Mocha',
    category: 'Statement',
    length: 'Long',
    shape: 'Coffin',
    finish: 'Cat eye',
    price: 1299,
    color: 'Mocha shimmer',
    tone: '#c2a08d',
    accentTone: '#cdbdff',
    description: 'A magnetic cat-eye set with a soft mocha base and moving light-shift effect.',
    story: 'Designed to catch light without becoming loud.',
    productionTime: '5–7 working days',
    featured: true,
  },
  {
    id: 'peach-cloud-bloom',
    code: 'BNB-004',
    name: 'Peach Cloud Bloom',
    category: 'Floral',
    length: 'Medium',
    shape: 'Almond',
    finish: 'Gloss',
    price: 1099,
    color: 'Peach',
    tone: '#ffd5bd',
    accentTone: '#f7c0dc',
    description: 'A warm peach floral set with tiny bloom details and a soft glassy top coat.',
    story: 'Sweet, detailed and still very wearable.',
    productionTime: '5–7 working days',
    featured: false,
  },
  {
    id: 'ivory-pearl-veil',
    code: 'BNB-005',
    name: 'Ivory Pearl Veil',
    category: 'Bridal',
    length: 'Medium',
    shape: 'Oval',
    finish: 'Pearl',
    price: 1499,
    color: 'Ivory pearl',
    tone: '#fff1de',
    accentTone: '#e3d7ff',
    description: 'A delicate ivory set with pearl finish, soft highlights and bridal-studio calm.',
    story: 'For days that need something graceful but not heavy.',
    productionTime: '6–8 working days',
    featured: true,
  },
  {
    id: 'berry-gloss-line',
    code: 'BNB-006',
    name: 'Berry Gloss Line',
    category: 'Everyday',
    length: 'Short',
    shape: 'Square',
    finish: 'Gloss',
    price: 699,
    color: 'Berry pink',
    tone: '#edaabd',
    accentTone: '#dacdff',
    description: 'A short square berry set with a clean line detail and practical everyday finish.',
    story: 'A little playful, a little polished.',
    productionTime: '3–5 working days',
    featured: false,
  },
  {
    id: 'lilac-chrome-ribbon',
    code: 'BNB-007',
    name: 'Lilac Chrome Ribbon',
    category: 'Chrome',
    length: 'Medium',
    shape: 'Almond',
    finish: 'Chrome',
    price: 1199,
    color: 'Lilac chrome',
    tone: '#cbb8ff',
    accentTone: '#ffd3e2',
    description: 'A cool lilac chrome set with ribbon-like reflective detailing.',
    story: 'Soft purple with a little futuristic shine.',
    productionTime: '5–7 working days',
    featured: false,
  },
  {
    id: 'mini-bow-blush',
    code: 'BNB-008',
    name: 'Mini Bow Blush',
    category: 'Cute',
    length: 'Short',
    shape: 'Round',
    finish: 'Gloss',
    price: 999,
    color: 'Blush bow',
    tone: '#ffcddd',
    accentTone: '#efe5ff',
    description: 'A short cute set with tiny bow accents and a clean blush base.',
    story: 'Playful without feeling childish.',
    productionTime: '4–6 working days',
    featured: false,
  },
];

export const categories = ['All', 'Minimal', 'French', 'Chrome', 'Floral', 'Bridal', 'Statement', 'Everyday', 'Cute'];
export const lengths = ['All', 'Short', 'Medium', 'Long', 'Same as shown'];
export const shapes = ['All', 'Almond', 'Oval', 'Square', 'Round', 'Coffin'];
export const finishes = ['All', 'Gloss', 'Chrome', 'Cat eye', 'Pearl', 'Matte'];
export const priceBands = ['All', 'Under ₹800', '₹800–₹1100', 'Above ₹1100'];
