-- BILLi&BoBA NAILS
-- Milestone 6B: Seed real products

insert into public.products (
  slug,
  name,
  design_code,
  category,
  description,
  studio_note,
  price_inr,
  compare_at_price_inr,
  shape,
  finish,
  length_options,
  tags,
  production_time_days,
  status,
  is_featured,
  sort_order
)
values
(
  'blush-boba-french',
  'Blush Boba French',
  'BNB-BBF-001',
  'French',
  'A soft blush french set with a clean everyday finish.',
  'Best for customers who want simple, cute and premium nails.',
  799,
  999,
  'Almond',
  'Glossy',
  array['Short', 'Medium', 'Long'],
  array['soft', 'french', 'blush', 'everyday'],
  7,
  'active',
  true,
  1
),
(
  'lavender-milk-glaze',
  'Lavender Milk Glaze',
  'BNB-LMG-002',
  'Glazed',
  'A pastel lavender glazed set with a smooth milky shine.',
  'A dreamy BILLi&BoBA style for soft glam looks.',
  899,
  1099,
  'Squoval',
  'Glazed',
  array['Short', 'Medium', 'Long'],
  array['lavender', 'glazed', 'pastel', 'soft glam'],
  7,
  'active',
  true,
  2
),
(
  'cat-eye-mocha',
  'Cat Eye Mocha',
  'BNB-CEM-003',
  'Cat eye',
  'A mocha-toned magnetic cat-eye set with a dimensional shine.',
  'For customers who want something deeper, sleek and eye-catching.',
  999,
  1199,
  'Coffin',
  'Cat eye',
  array['Medium', 'Long'],
  array['mocha', 'cat eye', 'magnetic', 'sleek'],
  8,
  'active',
  true,
  3
),
(
  'peach-cloud-chrome',
  'Peach Cloud Chrome',
  'BNB-PCC-004',
  'Chrome',
  'A peachy chrome set with soft cloud-like tones.',
  'Warm, cute and polished without looking too loud.',
  949,
  1199,
  'Almond',
  'Chrome',
  array['Short', 'Medium', 'Long'],
  array['peach', 'chrome', 'cloud', 'pastel'],
  8,
  'active',
  false,
  4
),
(
  'berry-bow-set',
  'Berry Bow Set',
  'BNB-BBS-005',
  'Cute',
  'A berry pink set with delicate bow-inspired detailing.',
  'Playful but still clean enough for daily wear.',
  1099,
  1299,
  'Almond',
  'Glossy',
  array['Medium', 'Long'],
  array['berry', 'bow', 'cute', 'pink'],
  9,
  'active',
  false,
  5
)
on conflict (slug)
do update set
  name = excluded.name,
  design_code = excluded.design_code,
  category = excluded.category,
  description = excluded.description,
  studio_note = excluded.studio_note,
  price_inr = excluded.price_inr,
  compare_at_price_inr = excluded.compare_at_price_inr,
  shape = excluded.shape,
  finish = excluded.finish,
  length_options = excluded.length_options,
  tags = excluded.tags,
  production_time_days = excluded.production_time_days,
  status = excluded.status,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  updated_at = now();